[package]
name = "apimachinery"
version = "0.1.0"
edition = "2024"

[dependencies]
k8s-openapi = { version = "0.25.0", features = ["v1_33"] }
reqwest = { version = "0.12.23", features = ["blocking", "json"] }